### ISSUE TITLE
Here's a docker compose

### ISSUE THREAD

**Issue by Nostradamus1973** [m0ngr31/ccEPG#1]
Good morning,

I was looking for an online version of this script vs a locally available one; I use IPTVeditor and although I could port forward things, it's a bit messy and less elegant than what I'm looking for. That being said I've been following your work that you've previously done with the EPlusTV for a few years now because I think you're quite talented. Even though I'm not using the EPlusTV script anymore and I can't use this ccEPG I whipped up a docker-compose.yml just in case any of your users feel like going that route.

```
services:
  ccepg:
    container_name: ccepg
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
    image: m0ngr31/ccepg
    ports:
      - 8787:8787    # Web Interface Port
    volumes:
      - /home/nostradamus/dockers/ccEPG/app/config:/app/config
    restart: unless-stopped
```
I added it to my home folder because this is how I've done it for years, but, anyone can change it to wherever they want it.
If for any reason you get Github to host the xml file I'll definitely use it.

Thanks again for all your hard work and have a great day.
